### ISSUE TITLE
Eva crashes when a csv file has extra columns

### ISSUE THREAD

**Issue by santiagose** [abtassociates/eva#154]
Hello! 

I keep receiving a "Disconnected from Server" message after my files are uploaded into EVA. The error message prompts you to reload the site but the issue keeps happending. Attached is a screenshot of the message itself.
![Screenshot 2023-01-17 081823](https://user-images.githubusercontent.com/41306500/212909068-e5c7df73-8388-4bf5-8ca2-273e0c6026fc.png)

Thanks!

Sergio Santiago
Tampa Hillsborough Homeless Initiative.

**Comment by kiadso** [comment]
Thank you for reporting this Sergio! We are investigating this and will get back to you as soon as we can.

**Comment by kiadso** [comment]
Hi @santiagose,

We are looking at logs, and we're wondering if you can reproduce the error and then tell us what time it was when it occurred so we can be sure we're looking at the right thing?

Thank you for your help with this!

**Comment by santiagose** [comment]
GM!

It has happened two me twice: Once was Saturday Friday 1/13 at around 8 PM and again yesterday the 17th at around 8 AM. I don’t remember the exact times but if you need anything else please let me know.

Thanks,

Sergio Santiago
Senior HMIS Manager
Tampa Hillsborough Homeless Initiative
PO Box 1110
Tampa, FL 33601-1110
________________

P: (813) 223-6115
D: (813) 274-6996
F: (813) 223-6178
E: ***@***.******@***.***>
W: THHI.org<http://www.hillsboroughcounty.org/>
Facebook: https://www.facebook.com/THHIorg
Twitter: https://www.twitter.com/THHIorg

***@***.***

The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.

**Comment by kiadso** [comment]
Thank you for the information. Just verifying- this happens every time you try to upload, correct?

**Comment by kiadso** [comment]
Also, are you uploading a .7z file or a .zip file? (It has to be a .zip file.)

**Comment by santiagose** [comment]
Gm!

Yes it is a .zip file.

Thanks,

Sergio Santiago
Senior HMIS Manager
Tampa Hillsborough Homeless Initiative
PO Box 1110
Tampa, FL 33601-1110
________________

P: (813) 223-6115
D: (813) 274-6996
F: (813) 223-6178
E: ***@***.******@***.***>
W: THHI.org<http://www.hillsboroughcounty.org/>
Facebook: https://www.facebook.com/THHIorg
Twitter: https://www.twitter.com/THHIorg

***@***.***

The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.

**Comment by santiagose** [comment]
It has happened every time unfortunately.

Thanks,

Sergio Santiago
Senior HMIS Manager
Tampa Hillsborough Homeless Initiative
PO Box 1110
Tampa, FL 33601-1110
________________

P: (813) 223-6115
D: (813) 274-6996
F: (813) 223-6178
E: ***@***.******@***.***>
W: THHI.org<http://www.hillsboroughcounty.org/>
Facebook: https://www.facebook.com/THHIorg
Twitter: https://www.twitter.com/THHIorg

***@***.***

The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.

**Comment by kiadso** [comment]
Thank you for the additional information Sonia! We are actively working on this and will update here when we know more.

Genelle

**Comment by alex-silverman** [comment]
Hi Sergio and Sonia,

Would you be able to send a screenshot of the contents of your zip file when you open it? It should look something like this:
![image](https://user-images.githubusercontent.com/3285721/213785335-ab51428f-1ad7-4200-93a0-b948fe8a3a28.png)

Also, a screenshot of the window you see when you're selecting the zip file to upload to the app, specifically showing the file path and the file extension. Like this:
![image](https://user-images.githubusercontent.com/3285721/213786028-258f469c-b5b9-491f-a371-5a5a9dce147d.png)

It may also help to have a conference call where we can screenshare. If either of you are interested and available, can you send a few times that could work for you to have such a call next week?

Finally, we have implemented a better way to connect our logs to users, which, with the info you provided on date and time of use, will help us diagnose these issues. Once we have those improvements up and running, we may ask you to give it another go so we can see what the log looks like when you're using it.

Alex

**Comment by soniawmeyer** [comment]
![image](https://user-images.githubusercontent.com/5512110/213806232-fa35e350-478c-40c0-825a-e9087df4df59.png)
![image](https://user-images.githubusercontent.com/5512110/213806346-966aed17-0271-4c97-a84c-eb41bb2571ad.png)
I'm generally available M-F 8 AM - 230 PM PST.

**Comment by santiagose** [comment]
Hello!

Please see attached screenshots for your review.

Regarding a meeting, I can be available Thursday morning.

Thanks,

Sergio Santiago
Senior HMIS Manager
Tampa Hillsborough Homeless Initiative
PO Box 1110
Tampa, FL 33601-1110
________________

P: (813) 223-6115
D: (813) 274-6996
F: (813) 223-6178
E: ***@***.******@***.***>
W: THHI.org<http://www.hillsboroughcounty.org/>
Facebook: https://www.facebook.com/THHIorg
Twitter: https://www.twitter.com/THHIorg

***@***.***

The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.

**Comment by alex-silverman** [comment]
@soniawmeyer - thank you for the screenshots. All of that looks good to me. You have all your CSV files inside of a .zip file.

@santiagose - I noticed that your zip file screenshot looked identical to @soniawmeyer's. Might you have accidentally sent her screenshot? Or are you working from the exact same system?

In any case, we are still working to better connect our logs to our users. Hoping to have that implemented today or tomorrow. Once we do so, I will reach back out here to see if you can test one more time before we schedule our calls. Worst case, we'll have more info to bring to those calls. Best, we'll have figured out the problem.

Thank you for bearing with us as we work through this issue!

**Comment by santiagose** [comment]
Hello,

Sonia and I are in different systems so the screenshots are unique. I’m not sure about Sonia’s system, but we use Clarity Human Services in our CoC (FL-501).

If you need anything else from me, please let me know.

Thanks,

Sergio Santiago
Senior HMIS Manager
Tampa Hillsborough Homeless Initiative
PO Box 1110
Tampa, FL 33601-1110
________________

P: (813) 223-6115
D: (813) 274-6996
F: (813) 223-6178
E: ***@***.******@***.***>
W: THHI.org<http://www.hillsboroughcounty.org/>
Facebook: https://www.facebook.com/THHIorg
Twitter: https://www.twitter.com/THHIorg

***@***.***

The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.

**Comment by soniawmeyer** [comment]
I am not able to see Sergio's screenshots. I use ETO.

**Comment by candiceh214** [comment]
I have gotten this error several times yesterday and again today.  It occurred after a successful upload using Firefox.  This morning this happened again today using Edge.  The file that I tried to upload locked up after "making lists" appears in the progress bar.

**Comment by alex-silverman** [comment]
@santiagose and @soniawmeyer  - Have either of you tried uploading again? Now that we have the more informative logs in place, knowing if/when (i.e. what day and time) you try again may help us better diagnose the issue.

@candiceh214 - Do you know roughly what time you tried uploading? This will help us "find you" in our server logs.

**Comment by santiagose** [comment]
Hello!

I tried again today at 2:50 PM today and I received the same error message as before.

Thanks,

Sergio Santiago
Senior HMIS Manager
Tampa Hillsborough Homeless Initiative
PO Box 1110
Tampa, FL 33601-1110
________________

P: (813) 223-6115
D: (813) 274-6996
F: (813) 223-6178
E: ***@***.******@***.***>
W: THHI.org<http://www.hillsboroughcounty.org/>
Facebook: https://www.facebook.com/THHIorg
Twitter: https://www.twitter.com/THHIorg

***@***.***

The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.

**Comment by soniawmeyer** [comment]
I got the same error 1/25/23 1:14 PM PST.

**Comment by candiceh214** [comment]
@alex-silverman I just attempted the files that were "crashing' and both uploaded with no issue!  Thanks!

**Comment by kiadso** [comment]
Hi @soniawmeyer and @santiagose can you please test your files again? We updated Eva at 10:40am this morning and the crashing issue was resolved for @candiceh214 so just want to be sure your issue was the same!

Thank you!

**Comment by santiagose** [comment]
GM!

I get the following error message when I go to https://hmis.abtsites.com/eva/:

“An error has occurred!
An error has occurred. Check your logs or contact the app author for clarification.”

Thanks,

Sergio Santiago
Senior HMIS Manager
Tampa Hillsborough Homeless Initiative
PO Box 1110
Tampa, FL 33601-1110
________________

P: (813) 223-6115
D: (813) 274-6996
F: (813) 223-6178
E: ***@***.******@***.***>
W: THHI.org<http://www.hillsboroughcounty.org/>
Facebook: https://www.facebook.com/THHIorg
Twitter: https://www.twitter.com/THHIorg

***@***.***

The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.

**Comment by kiadso** [comment]
@santiagose 

Thank you so much for letting us know! We are working on it right now.

**Comment by kiadso** [comment]
Ok, Eva is back up, please try again! @santiagose @soniawmeyer 

Thank you!

**Comment by santiagose** [comment]
Sorry, but I’m still getting an error message (please see attached).

Thanks,

Sergio Santiago
Senior HMIS Manager
Tampa Hillsborough Homeless Initiative
PO Box 1110
Tampa, FL 33601-1110
________________

P: (813) 223-6115
D: (813) 274-6996
F: (813) 223-6178
E: ***@***.******@***.***>
W: THHI.org<http://www.hillsboroughcounty.org/>
Facebook: https://www.facebook.com/THHIorg
Twitter: https://www.twitter.com/THHIorg

***@***.***

The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.

**Comment by kiadso** [comment]
Hi @santiagose I'm not seeing your attachment- can you put the text of the error in your comment?

**Comment by santiagose** [comment]
Hello,

The error reads “Your session timed out, reload the application” and includes a “Refresh” Link.

Thanks,

Sergio Santiago
Senior HMIS Manager
Tampa Hillsborough Homeless Initiative
PO Box 1110
Tampa, FL 33601-1110
________________

P: (813) 223-6115
D: (813) 274-6996
F: (813) 223-6178
E: ***@***.******@***.***>
W: THHI.org<http://www.hillsboroughcounty.org/>
Facebook: https://www.facebook.com/THHIorg
Twitter: https://www.twitter.com/THHIorg

***@***.***

The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.

**Comment by kiadso** [comment]
Hi Sergio,

Whenever you go to Eva, if you let the site go idle for 10 minutes, it should return that exact warning. When you click "Refresh," does Eva reload and allow you to upload your file? @santiagose 

Thanks-

Genelle

**Comment by santiagose** [comment]
Hey Genelle,

I tried to upload it ASAP and it still should this error after the upload, even though it wasn’t idling long enough to trigger this pop up.


Thanks,



Sergio Santiago

Senior HMIS Manager

Tampa Hillsborough Homeless Initiative

PO Box 1110

Tampa, FL 33601-1110

________________



P: (813) 223-6115

D: (813) 274-6996

F: (813) 223-6178

E: ***@***.******@***.***>

W: THHI.org<http://www.hillsboroughcounty.org/>

Facebook: https://www.facebook.com/THHIorg

Twitter: https://www.twitter.com/THHIorg



[Image]



The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.

________________________________

**Comment by kiadso** [comment]
Hi Sergio, what is your operating system?

**Comment by alex-silverman** [comment]
Sergio, do you have any time today to have a call and a screenshare? I'm wondering if we can walk through some debugging steps together, since we cannot replicate this issue on our end.

**Comment by santiagose** [comment]
I can do 2:30 pm today if that works for you all. My OS is 64-but Windows 10 enterprise.


Thanks,



Sergio Santiago

Senior HMIS Manager

Tampa Hillsborough Homeless Initiative

PO Box 1110

Tampa, FL 33601-1110

________________



P: (813) 223-6115

D: (813) 274-6996

F: (813) 223-6178

E: ***@***.******@***.***>

W: THHI.org<http://www.hillsboroughcounty.org/>

Facebook: https://www.facebook.com/THHIorg

Twitter: https://www.twitter.com/THHIorg



[Image]



The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.

________________________________

**Comment by alex-silverman** [comment]
that works! Here's a link to a Microsoft Teams meeting:

https://teams.microsoft.com/l/meetup-join/19%3ameeting_MjFhMzZiM2YtODk1ZS00MDc1LWFkNTgtM2Y5ZjhhNWRjMmM2%40thread.v2/0?context=%7b%22Tid%22%3a%22ce6f901a-3a80-4987-a685-9d4d96f1f180%22%2c%22Oid%22%3a%227c71515e-7f7d-42cb-bba7-914ab6cfdff6%22%7d

I think there's a browser-based version if you don't have Teams.

**Comment by kiadso** [comment]
@santiagose Thank you again for your time this afternoon and helping us sort out the issues. To document our findings:

- Sergio's export had a number of extra files. This was not the problem.
- The export's YouthEducationStatus file had 0 rows. Also not the problem!
- The Assessment file and the Services file each had extra columns. <- this was the problem.
- Once the extra columns were removed, Eva did not crash but did reject the file with information about other high priority issues:
     - Null EntryDates in the Enrollment file
     - Either null InformationDates in the HealthAndDV and IncomeBenefits files or those dates are the incorrect date type.

Sergio will follow up with his vendor regarding these issues and Abt will work to improve Eva on handling extra columns more gracefully.

We will follow up here whenever the crashing issue is fully resolved for Sergio.

**Comment by soniawmeyer** [comment]
Mine worked! Thank you!

**Comment by santiagose** [comment]
Hey  everyone,

Quick update; I still get an error about the GrantID column in the Funder file (please see attached). Here is the response from Bitfocus:

"For the GrantID column in the Funder file issue, our Reporting Team noted that there are No Null Values for the file - All characters appear to be allowable and within the S32 Data Type requirements. The Reporting Team has reported issues surrounding GrantID and another vendor has submitted this issue here<https://github.com/abtassociates/eva/issues/150>. It was noted in the conversation in the link that this has been updated to be an error that would not cause a file to be rejected."

Can you look into this when you get a chance, please?

Thanks,

Sergio Santiago
Senior HMIS Manager
Tampa Hillsborough Homeless Initiative
PO Box 1110
Tampa, FL 33601-1110
________________

P: (813) 223-6115
D: (813) 274-6996
F: (813) 223-6178
E: ***@***.******@***.***>
W: THHI.org<http://www.hillsboroughcounty.org/>
Facebook: https://www.facebook.com/THHIorg
Twitter: https://www.twitter.com/THHIorg

***@***.***

The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.

**Comment by santiagose** [comment]
Done, thanks!

Sergio Santiago
Senior HMIS Manager
Tampa Hillsborough Homeless Initiative
PO Box 1110
Tampa, FL 33601-1110
________________

P: (813) 223-6115
D: (813) 274-6996
F: (813) 223-6178
E: ***@***.******@***.***>
W: THHI.org<http://www.hillsboroughcounty.org/>
Facebook: https://www.facebook.com/THHIorg
Twitter: https://www.twitter.com/THHIorg

***@***.***

The information transmitted is intended only for the named person or entity only. This message may contain confidential, proprietary or legally privileged material. If you have received this message in error please contact the sender, and delete all affiliations with this e-mail immediately. Any review, use, disclose, distribution or other use of this e-mail is prohibited.
